[package]
name = "printer_status"
version = "0.1.0"
edition = "2021"

[dependencies]
wmi = "0.13.1"
serde = { version = "1.0", features = ["derive"] }
windows-sys = { version = "0.52", features = ["Win32_System_Console"] }
